# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: nils.theeten@epfl.ch
author_name: Nils Theeten
github_org: NilsTheeten
package_name: hydroponics
project_name: hydroponics
short_description: Simulation of hydroponic farming
